name: "Auto Tagging (Reusable)"
on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string
      commit_version:
        required: true
        type: string
      commit_action:
        required: true
        type: string

# Required Secrets
# - BOT_GPG_PRIVATE_KEY
# - BOT_GPG_PASSPHRASE

jobs:
  # check_version:
  #   uses: ./.github/workflows/check-version.yml

  create_release_tag:
    # needs: check_version
    if: >
      github.ref_name == 'main' &&
      inputs.commit_version != '' &&
      inputs.commit_action == 'r'

    outputs:
      tag_name: ${{ steps.create_tag.outputs.tag_name }}   # reference step output

    name: "Create Tags"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: ${{ github.workspace }}
      - name: Create git tag
        id: create_tag
        run: |
          TAG=${{ needs.check_version.outputs.commit_version }}
          git tag $TAG ${{ inputs.commit_sha }}
          git push origin $TAG
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

