name: "Update Documentation (Reusable)"
on:
  workflow_call:

jobs:
  update_docs:
    name: "Update Documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Install Doxygen and PlantUML
      #   run: sudo apt-get update && sudo apt-get install -y doxygen plantuml

      - name: Generate docs
        run: |
          echo "GENERATE DOCUMENTATION"